package com.harmonymod.util;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Utility class for advanced logging in Harmony.
 * Supports custom log levels and easy message formatting.
 */
public class HarmonyLogger {
    private final Logger logger;

    public HarmonyLogger(String name) {
        this.logger = LoggerFactory.getLogger(name);
    }

    public void info(String message, Object... args) {
        logger.info(message, args);
    }

    public void debug(String message, Object... args) {
        logger.debug(message, args);
    }

    public void warn(String message, Object... args) {
        logger.warn(message, args);
    }

    public void error(String message, Object... args) {
        logger.error(message, args);
    }

    public void trace(String message, Object... args) {
        logger.trace(message, args);
    }
}
