modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="harmony"
version="1.0.0"
displayName="Harmony"
authors="YourName"
description='''
Harmony: Mod mediator for Minecraft worldgen!
'''
