modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
[[mods]]
modId="harmonymod"
version="1.0.0"
displayName="Harmony"
displayURL="https://github.com/yourname/harmonymod"
logoFile="harmony.png"
authors="Your Name"
description='''
A universal worldgen and structure claim mediator for Minecraft modding.
Simplifies biome/structure feature claims, ensures compatibility, and adds handy APIs for modders.
'''
