# Harmony Main Configuration

[general]
# If true, Harmony will log every claim and permission check for debugging.
logAllClaims = false

# If true, Harmony will allow mods to "force-claim" a biome or structure, overriding previous claims (not recommended for public mods).
allowForceClaim = false

# List of modids that are always prioritized for claims (comma-separated).
priorityMods = "harmonymod"

[worldgen]
# If true, Harmony will block worldgen changes in vanilla biomes unless claimed.
blockVanillaBiomeChanges = true

# If true, Harmony will block structure changes in vanilla structures unless claimed.
blockVanillaStructureChanges = true

# List of vanilla biomes/structures that are always open for modification (comma-separated ResourceLocations).
openVanillaBiomes = "minecraft:plains,minecraft:forest"
openVanillaStructures = "minecraft:village"
